blog_main/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from blogs import views as blogsviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('category/', include('blogs.urls')),
    path('blogs/search/',blogsviews.search,name='search'),
    path('blogs/<slug:slug>/',blogsviews.blogs,name='blogs'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('dashboard/', include('dashboards.urls'))

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from .import views


urlpatterns=[
    path('<int:category_id>/',views.posts_by_category,name='posts_by_category'),

]

dashboards/urls.py
from django.urls import path
from .import views

urlpatterns=[
    path('',views.dashboard,name='dashboard'),
    path('categories/',views.categories,name='categories'),
    path('categories/add/',views.add_category,name='add_category'),
    path('categories/edit/<int:pk>/',views.edit_category,name='edit_category'),
    path('categories/delete/<int:pk>/',views.delete_category,name='delete_category'),
    path('posts/',views.posts,name='posts'),
    path('posts/add/',views.add_posts,name='add_posts'),
    path('posts/edit/<int:pk>/',views.edit_posts,name='edit_posts'),
    path('posts/delete/<int:pk>/',views.delete_posts,name='delete_posts'),
    path('users/',views.users,name='users'),
    path('users/add/',views.add_users,name='add_users'),
    path('users/edit/<int:pk>/',views.edit_users,name='edit_users'),
    path('users/delete/<int:pk>/',views.delete_users,name='delete_users')
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    category_name=models.CharField(max_length=50,unique=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural='categories'


    def __str__(self):
        return self.category_name
STATUS_CHOICES=(
    ('Draft','Draft'),
    ('Published','Published')
)
    
class Blog(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField(max_length=150,unique=True,blank=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    featured_image=models.ImageField(upload_to='uploads/%Y/%m/%d')
    short_description=models.TextField(max_length=500)
    blog_body=models.TextField(max_length=2000)
    status=models.CharField(max_length=20,choices=STATUS_CHOICES,default='Draft')
    is_featured=models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title
    
class Comments(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    blog=models.ForeignKey(Blog,on_delete=models.CASCADE)
    comments=models.TextField(max_length=250)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comments
    

    
    

dashboards/models.py
from django.db import models

# Create your models here.

dashboards/forms.py
from django import forms
from blogs.models import Category,Blog
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class AddForm(forms.ModelForm):
    class Meta:
        model=Category
        fields='__all__'

class AddBlogForm(forms.ModelForm):
    class Meta:
        model=Blog
        fields=('title','short_description','blog_body','featured_image','status','category','is_featured')

class AddUserForm(UserCreationForm):
    class Meta:
        model=User
        fields=('username','first_name','last_name','email','is_active','is_staff','is_superuser','groups','user_permissions')

class EditUserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('username','first_name','last_name','email','is_active','is_staff','is_superuser','groups','user_permissions')

dashboards/views.py
from django.shortcuts import render,redirect,get_object_or_404
from blogs.models import Blog,Category
from django.contrib.auth.decorators import login_required
from .forms import AddForm,AddBlogForm,AddUserForm,EditUserForm
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
# Create your views here.
@login_required(login_url='login')
def dashboard(request):
    category=Category.objects.all()
    blogs=Blog.objects.all()

    context={
        'blogs':blogs,
        'category':category
    }


    return render(request,'dashboard/dashboard.html',context)

def categories(request):
    return render(request,'dashboard/categories.html')

def add_category(request):
    if request.method=='POST':
        form=AddForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('categories')
    else:
        form=AddForm()
    context={
        'form':form,
    }

    return render(request,'dashboard/add_category.html',context)

def edit_category(request,pk):
    category=get_object_or_404(Category,pk=pk)
    if request.method=='POST':
        form=AddForm(request.POST,instance=category)
        if form.is_valid():
            form.save()
            return redirect('categories')
    else:
        form=AddForm(instance=category)

    context={
        'form':form,
        'category':category
    }

    return render(request,'dashboard/edit_category.html',context)

def delete_category(request,pk):
    category=get_object_or_404(Category,pk=pk)
    category.delete()
    return redirect('categories')

def posts(request):
    return render(request,'dashboard/posts.html')


def add_posts(request):
    if request.method=='POST':
        form=AddBlogForm(request.POST,request.FILES)
        if form.is_valid():
            post=form.save(commit=False) # Temporarily saving the form
            post.author=request.user
            post.save() #then saving for generating pk/id
            title=form.cleaned_data['title']
            post.slug=slugify(title)+'-'+str(post.id) #making the slug unique by suffixing post.id(unique) 
            post.save()
            return redirect('posts')
    else:
        form=AddBlogForm()

    context={
        'form':form
    }
    return render(request,'dashboard/add_posts.html',context)

def edit_posts(request,pk):
    post=get_object_or_404(Blog,pk=pk)

    if request.method=='POST':
        post_form=AddBlogForm(request.POST,request.FILES,instance=post)
        if post_form.is_valid():
            form=post_form.save()
            title=post_form.cleaned_data['title']
            form.slug=slugify(title)+'-'+str(form.id)
            form.save()
            return redirect('posts')
    else:
        post_form=AddBlogForm(instance=post)
    context={
        'post_form':post_form,
        'post':post

    }
    return render(request,'dashboard/edit_posts.html',context)

def delete_posts(request,pk):
    post=get_object_or_404(Blog,pk=pk)
    post.delete()
    return redirect('posts')

def users(request):
    users=User.objects.all()
    context={
        'users':users
    }
    return render(request,'dashboard/users.html',context)

def add_users(request):
    if request.method=='POST':
        form=AddUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users')
    form=AddUserForm()

    context={
        'form':form
    }

    return render(request,'dashboard/add_users.html',context)

def edit_users(request,pk):
    user=get_object_or_404(User,pk=pk)
    if request.method=='POST':
        form=EditUserForm(request.POST,instance=user)
        if form.is_valid():
            form.save()
            return redirect('users')
    else:
        form=EditUserForm(instance=user)
    context={
        'form':form
    }
    return render(request,'dashboard/edit_users.html',context)

def delete_users(request,pk):
    user=get_object_or_404(User,pk=pk)
    user.delete()
    return redirect('users')


        

    

templates/dashboard/add_category.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<div class="row">
     {% if perms.blogs.add_category %}
      {% include 'dashboard/sidebar.html' %}

<div class="col-md-9">
  
        <h2 class="text">Add New Category</h2>

        <form action="{% url 'add_category' %}" method="POST" style="width: 500px;">
            {% csrf_token %}

            {{ form | crispy }}

            <button type="submit" class="btn btn-warning">Submit</button>


        </form>

       
       
    </div>
    {% else %}
     <h4>Why are you wasting time? I said earlier also you dont have permission.</h4>
    {% endif %}
</div>




{% endblock %}

templates/dashboard/add_posts.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<div class="row">
      {% include 'dashboard/sidebar.html' %}
<div class="col-md-9">
  
        <h2 class="text">Add New Blog</h2>

        <form action="{% url 'add_posts' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form | crispy }}

            <button type="submit" class="btn btn-warning">Submit</button>


        </form>

       
       
    </div>
</div>




{% endblock %}

templates/dashboard/add_users.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<div class="row">
      {% include 'dashboard/sidebar.html' %}
<div class="col-md-9">
    {% if perms.auth.add_user %}
  
        <h2 class="text">Add New Users</h2>

        <form action="{% url 'add_users' %}" method="POST">
            {% csrf_token %}

            {{ form | crispy }}

            <button type="submit" class="btn btn-warning">Submit</button>


        </form>

       {% else %}
       <h5>You dont have the permission to view this page</h5>
       {% endif %}
       
    </div>
</div>




{% endblock %}

templates/dashboard/categories.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    {% if perms.blogs.add_category %}
    {% include 'dashboard/sidebar.html' %}
    <div class="col-md-9">
        <h2>All Categories</h2>
        <a href="{% url 'add_category' %}" class="btn btn-dark text-light float-right mb-2">Add New</a>
        <table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Category Name</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Action</th>
    </tr>
  </thead>
  
  <tbody>
    {% for cat in categories %}
    <tr>
      <th>{{forloop.counter}}</th>
      <td>{{cat}}</td>
      <td>{{cat.created_at}}</td>
      <td>{{cat.updated_at}}</td>
      <td>
          <a href="{% url 'edit_category' cat.id %}"><i class="fa fa-edit text-success"></i></a>
        &nbsp;
          <a href="{% url 'delete_category' cat.id %}"><i class="fa fa-trash text-danger"></i></a>
    </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
       
    </div>
    {% else %}
    <h4>You dont have permissions to view this page.</h4>
    {% endif %}
</div>




{% endblock %}

templates/dashboard/dashboard.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    {% if perms.blogs.add_blog %}
    {% include 'dashboard/sidebar.html' %}
    <div class="col-md-9">
        <span>Logged in as: <b>{{user}}</b></span>
        <div class="row">
            <div class="col">
                <div class="card border-default mb-3">
                    <div class="card-header text-center text-uppercase font-weight-bold"> All Categories</div>
                    <div class="card-body text-dark"><h5 class="card-title text-center">{{category.count}}</h5></div>
                </div>
            </div>
            <div class="col">
                <div class="card border-default mb-3">
                    <div class="card-header text-center text-uppercase font-weight-bold"> All posts</div>
                    <div class="card-body text-dark ">
                        <h5 class="card-title text-center">{{blogs.count}}</h5>
                    </div>
    
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <h4>You dont have permissions to view this page.</h4>
    {% endif %}
</div>




{% endblock %}

templates/dashboard/edit_category.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<div class="row">
     {% if perms.blogs.change_category %}
      {% include 'dashboard/sidebar.html' %}
<div class="col-md-9">
  
        <h2 class="text">Edit Category</h2>

        <form action="{% url 'edit_category' category.id %}" method="POST" style="width: 500px;">
            {% csrf_token %}

            {{ form | crispy }}

            <button type="submit" class="btn btn-warning">Submit</button>


        </form>

    </div>
    {% else %}
     <h4>Why are you wasting time? I said earlier also you dont have permission.</h4>
    {% endif %}
</div>




{% endblock %}

templates/dashboard/edit_posts.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<div class="row">
    {% if perms.auth.change_posts %}
      {% include 'dashboard/sidebar.html' %}
<div class="col-md-9">
  
        <h2 class="text">Edit Post</h2>

        <form action="{% url 'edit_posts' post.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {{ post_form | crispy }}

            <button type="submit" class="btn btn-warning">Submit</button>


        </form>
       
    </div>
    {% else %}
    <h4>You dont have permission to view this page.</h4>
    {% endif %}
</div>

{% endblock %}

templates/dashboard/edit_users.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<div class="row">
      {% include 'dashboard/sidebar.html' %}
<div class="col-md-9">
    {% if perms.auth.change_user %}
  
        <h2 class="text"> Edit User</h2>

        <form action="{% url 'add_users' %}" method="POST">
            {% csrf_token %}

            {{ form | crispy }}

            <button type="submit" class="btn btn-warning">Submit</button>


        </form>

       {% else %}
       <h5>You dont have the permission to view this page</h5>
       {% endif %}
       
    </div>
</div>




{% endblock %}

templates/dashboard/posts.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    {% if perms.blogs.add_blog %}
    {% include 'dashboard/sidebar.html' %}
    <div class="col-md-9">
        <h2>All Blog Posts</h2>
        <a href="{% url 'add_posts' %}" class="btn btn-dark text-light float-right mb-2">Add New</a>
        <table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Category</th>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th>Featured</th>
      <th>Action</th>
    </tr>
  </thead>
  
  <tbody>
    {% for blog in blogs %}
    <tr>
      <th>{{forloop.counter}}</th>
      <td>{{blog.category}}</td>
      <td>{{blog.title}}</td>
      <td>{{blog.author}}</td>
      <td>{{blog.status}}</td>
      <td>{% if blog.is_featured %}<i class="fa fa-check text-success"></i>{% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
      <td>
          <a href="{% url 'edit_posts' blog.id %}"><i class="fa fa-edit text-success"></i></a>
        &nbsp;
          <a href="{% url 'delete_posts' blog.id %}"><i class="fa fa-trash text-danger"></i></a>
    </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
       
    </div>
    {% else %}
    <h4>You dont have permission to view this page.</h4>
    {% endif %}
</div>




{% endblock %}

templates/dashboard/sidebar.html
<div class="col-md-3">
        <div class="nav flex-column nav-pills bg-light" aria-orientation="vertical">
            <a href="{% url 'dashboard' %}" class="nav-link text-dark {% if '/dashboard/' == request.path %}bg-warning {% endif %}">Dashboard</a>
            {% if perms.auth.view_user %}
            <a href="{% url 'users'  %}" class="nav-link text-dark {% if '/users/' in request.path %}bg-warning {% endif %}">Users</a>
            {% endif %}
            <a href="{% url 'categories' %}" class="nav-link text-dark {% if '/categories/' in request.path %}bg-warning {% endif %}">Categories</a>
            <a href="{% url 'posts'  %}" class="nav-link text-dark {% if '/posts/' in request.path %}bg-warning {% endif %}">Posts</a>

            <a href="{% url 'logout' %}" class="nav-link text-dark">Logout</a>
        </div>
    </div> 

templates/dashboard/users.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
    {% include 'dashboard/sidebar.html' %}
    <div class="col-md-9">
        {% if perms.auth.view_user %}
        <h2>All Users</h2>
        <a href="{% url 'add_users' %}" class="btn btn-dark text-light float-right mb-2">Add New</a>
        <table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>username</th>
      <th>Full Name</th>
      <th>Email Address</th>
      <th>Active</th>
      <th>Staff</th>
      <th>Superuser</th>
      <th>Action</th>
    </tr>
  </thead>
  
  <tbody>
    {% for user in users %}
    <tr>
      <th>{{forloop.counter}}</th>
      <td>{{user.username}}</td>
      <td>{{user.first_name}} {{user.last_name}}</td>
      <td>{{user.email}}</td>
      <td>{% if user.is_active %}<i class="fa fa-check text-success"></i> {% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
      <td>{% if user.is_staff %}<i class="fa fa-check text-success"></i> {% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
      <td>{% if user.is_superuser %}<i class="fa fa-check text-success"></i> {% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
      <td>
          <a href="{% url 'edit_users' user.pk %}"><i class="fa fa-edit text-success"></i></a>
        &nbsp;
          <a href="{% url 'delete_users' user.pk %}"><i class="fa fa-trash text-danger"></i></a>
    </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
       
    </div>
    {% else %}
    <h5>You dont have the permission to view this page.</h5>
    {% endif %}
</div>



{% endblock %}